In [37]:
import numpy as np

keypoint_KD = np.arange(12).reshape((4,3))
mask = np.array([False,False,False,False])

keypoint_KD[mask,:]

array([], shape=(0, 3), dtype=int64)

In [54]:

keypoint_mask_K = np.array([True, False,True, False,True, False,True, False,True, False,])
SKELETAL_LINE_PAIRS_LIST = [(4,2),(2,0),(0,1),(1,3),
                            (10,8),(8,6),(6,5),(5,7),(7,8),
                            (6,12),(12,14),(14,16),(5,11),(11,13),(13,15),(12,11)]
K = keypoint_mask_K.shape[0]
include_list = np.arange(K)[keypoint_mask_K].astype(np.int32)
filtered_list = [pair for pair in SKELETAL_LINE_PAIRS_LIST 
                    if pair[0] in include_list and pair[1] in include_list]

for valid_pair in filtered_list:
    print(keypoint_mask_K[valid_pair[0]])


# filtered_list = [pair for pair in SKELETAL_LINE_PAIRS_LIST 
                #  if not (pair[0] in exclude_list or pair in exclude_list)]


In [27]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

x = car.items()

for key, value in car.items():
    print(key, value)

brand Ford
model Mustang
year 1964


In [35]:
import sys

# Create a dictionary
my_dict = {'a': 1, 'b': 2, 'c': 3, 'd': 4}
print(sys.getsizeof(my_dict))
# Delete specific elements from the dictionary


del my_dict['a']
print(sys.getsizeof(my_dict))

del my_dict['b']
print(sys.getsizeof(my_dict))

my_dict['c'] = None
print(sys.getsizeof(my_dict))
    
del my_dict['c']
print(sys.getsizeof(my_dict))

232
232
232
232
232


In [12]:
import torch
# from torch import Tensor
import numpy as np

a = np.array([1,2],dtype=np.int16)
b = torch.randn((2,),device='cuda:0')

print(a,b)
a[0] = b[0]
print(type(a[0]))

[1 2] tensor([-0.9601, -2.7959], device='cuda:0')
<class 'numpy.int16'>


In [15]:
import numpy as np
from feature_extractor.KalmanFilter import KalmanFilter

a = np.empty(17, dtype=object)
for i in range(17):
    a[i] = KalmanFilter()

print(a)

In [19]:
import numpy as np
keypoints_2d = np.array([
    [0.00, 0.00, 0.10],
    [0.00, 0.00, 0.10],
    [0.00, 0.00, 0.10],
    [700, 500, 0.9],
    [700, 500, 0.9],
    [700, 500, 0.9],
    [700, 500, 0.9],
    [0.00, 0.00, 0.10],
    [0.00, 0.00, 0.10],
    [0.00, 0.00, 0.10],

])
valid_xy = keypoints_2d[:,:2] != int(0)        # bool [K,2]
valid_keypoint = valid_xy[:,0] & valid_xy[:,1]
print(valid_xy)
print(valid_keypoint)

[[False False]
 [False False]
 [False False]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [False False]
 [False False]
 [False False]]
[False False False  True  True  True  True False False False]


In [33]:
from std_msgs.msg import Int16MultiArray
import numpy as np
import time

keypoints_3d = np.random.random((2, 2, 3))
id_human = np.array([3,4,5,6,7])


a = {1:keypoints_3d, 2:id_human}
b =  a.setdefault(1, keypoints_3d)
print(b)
b = np.zeros_like(keypoints_3d)
print(a)

[[[0.11113873 0.59743193 0.9495511 ]
  [0.87999633 0.70648137 0.12723671]]

 [[0.33335164 0.96645536 0.6369063 ]
  [0.89202902 0.55118741 0.12110179]]]
{1: array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]]), 2: array([3, 4, 5, 6, 7])}


In [ ]:
import numpy as np
import cv2

width = 11
height = 11
shape = cv2.MORPH_RECT
kernel = cv2.getStructuringElement(shape, (height,width))


cx = 10 
cy = 10

top_left_x = cx - (width >> 1)
top_left_y = cy - (width >> 1)

bottom_right_x = top_left_x + width
bottom_right_y = top_left_y + height



In [15]:
original
    xy=780*1280
    0,1 = 1280, 780

rotate
    xy=1280*780
    0,1 = 780,1280

keypoint
    [0] = 5.0851e+02, 1.4669e+02, 9.9753e-01 top_right
            [508 in 720, 146 in 1280]
            ----> axis 0
            |
            |
            v axis 1

IndexError: index 3 is out of bounds for axis 0 with size 3

In [21]:
import cv2
import numpy as np

data = np.random.random((1, 17, 3))*10
mask = np.random.choice(a=[False, True], size=(1, 17), p=[0.5, 1-0.5])

sample = np.where(mask[:,:,None], data, np.nan)

print(data)
print(mask)
print(sample)

[[[2.91775114 6.10476421 6.41001519]
  [7.34542165 5.94355781 9.18747296]
  [1.47402257 4.33508797 0.73098969]
  [5.35237664 7.97577351 9.38956923]
  [4.46478577 8.28913708 5.34859324]
  [6.31552542 3.64956034 7.23027127]
  [8.5166189  8.74732116 6.41036651]
  [9.61869479 7.12133832 6.55032313]
  [6.84969841 0.6692899  9.01670255]
  [6.16338933 3.88367633 0.53500447]
  [4.53935993 8.85656157 6.57543627]
  [3.41643023 1.25915325 7.31595912]
  [9.89712057 4.14074091 0.50070669]
  [8.29624293 4.24467046 0.77903447]
  [0.44733331 9.48535999 3.84321361]
  [8.98807987 0.96280896 9.26599231]
  [3.07717514 9.28498655 4.80896723]]]
[[False False False False  True False  True False False  True False False
  False  True  True False False]]
[[[       nan        nan        nan]
  [       nan        nan        nan]
  [       nan        nan        nan]
  [       nan        nan        nan]
  [4.46478577 8.28913708 5.34859324]
  [       nan        nan        nan]
  [8.5166189  8.74732116 6.41036651]
  

In [22]:
a = []
a.append(None)
a.append(None)

a.append(None)
a

[None, None, None]

In [11]:
scores1 = np.array([[[1.,2.],[3.,4.],[5.,6.]],[[11.,12.],[13.,14.],[15.,16.]]],dtype='float32')
scores2 = np.array([[[1.,2.],[3.,4.],[5.,6.]],[[11.,12.],[13.,14.],[15.,16.]]],dtype=np.float32)

print(scores1.dtype)
print(scores2.dtype)

float32
float32


In [16]:
a = None
K = 17
a = np.empty(K,dtype=object)
a = None

if a is not None:
    print("not None")

In [23]:
import pickle

file = open('/home/xmo/socialnav_xmo/feature_extractor/tests/test.pkl','wb')
scores1 = np.array([[[1.,2.],[3.,4.],[5.,6.]],[[11.,12.],[13.,14.],[15.,16.]]],dtype='float32')

obj_1 = ['test_1', {'ability', 'mobility'},scores1]
obj_2 = ['test_2', {'ability', 'mobility'}]
obj_3 = ['test_3', {'ability', 'mobility'}]

pickle.dump(obj_1, file)
pickle.dump(obj_2, file)
pickle.dump(obj_3, file)

file.close()

file = open('test.pkl', 'rb')
obj_1 = pickle.load(file)
obj_2 = pickle.load(file)
obj_3 = pickle.load(file)
print(obj_1)
print(obj_2)
print(obj_3)
file.close()

['test_1', {'mobility', 'ability'}, array([[[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]],

       [[11., 12.],
        [13., 14.],
        [15., 16.]]], dtype=float32)]
['test_2', {'mobility', 'ability'}]
['test_3', {'mobility', 'ability'}]


In [31]:
a:np.array
a = a.astype(bool)
a[0] = np.zeros(5)
a

ValueError: setting an array element with a sequence.