In [8]:
import numpy as np

a = np.random.random((3,4))
print(a.astype(np.int16))
# a = np.zeros_like(a)
b = a >= 0.5

# # print(b[:,0:1].shape)
# print(a)
# print(b)
# print(a[b[:,0], : ])    # vector
# print(a[b[:,0:1], : ])    # vector

Sigma : np.ndarray = None           # Covariance A
# Sigma = np.array([1,2,3])
# Sigma

a = np.random.random((3,4)).astype(np.float128)
b = np.random.random((3,4)).astype(np.float64)

(a + b).dtype

type(np.float16(1))

a = np.arange(9)
assert a.shape == (9) , 'shape of depth must be (K,)'


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


AssertionError: shape of depth must be (K,)

In [25]:
class ppp:
    def __init__(self) -> None:
        self.b = 10000

a = dict()
a[1] = ppp()
a[2] = ppp()
a[100] = ppp()

a

{1: <__main__.ppp at 0x7f8a77522200>,
 2: <__main__.ppp at 0x7f8a77520c10>,
 100: <__main__.ppp at 0x7f8a775210f0>}

In [27]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

x = car.items()

for key, value in car.items():
    print(key, value)

brand Ford
model Mustang
year 1964


In [35]:
import sys

# Create a dictionary
my_dict = {'a': 1, 'b': 2, 'c': 3, 'd': 4}
print(sys.getsizeof(my_dict))
# Delete specific elements from the dictionary


del my_dict['a']
print(sys.getsizeof(my_dict))

del my_dict['b']
print(sys.getsizeof(my_dict))

my_dict['c'] = None
print(sys.getsizeof(my_dict))
    
del my_dict['c']
print(sys.getsizeof(my_dict))

232
232
232
232
232


In [26]:
import numpy as np

a = np.array([True, False]).astype(np.int16)
print(type(a[0]))

<class 'numpy.bool_'>


In [15]:
import numpy as np
from feature_extractor.KalmanFilter import KalmanFilter

a = np.empty(17, dtype=object)
for i in range(17):
    a[i] = KalmanFilter()

print(a)

In [19]:
import numpy as np
keypoints_2d = np.array([
    [0.00, 0.00, 0.10],
    [0.00, 0.00, 0.10],
    [0.00, 0.00, 0.10],
    [700, 500, 0.9],
    [700, 500, 0.9],
    [700, 500, 0.9],
    [700, 500, 0.9],
    [0.00, 0.00, 0.10],
    [0.00, 0.00, 0.10],
    [0.00, 0.00, 0.10],

])
valid_xy = keypoints_2d[:,:2] != int(0)        # bool [K,2]
valid_keypoint = valid_xy[:,0] & valid_xy[:,1]
print(valid_xy)
print(valid_keypoint)

[[False False]
 [False False]
 [False False]
 [ True  True]
 [ True  True]
 [ True  True]
 [ True  True]
 [False False]
 [False False]
 [False False]]
[False False False  True  True  True  True False False False]


In [22]:
from std_msgs.msg import Int16MultiArray
import numpy as np
import time
id_human = np.arange(10).astype(np.int16)
# id_human = range(10)
id_msg = Int16MultiArray()
# id_msg.data = list()
t1 = time.time()
for id in id_human:
    id_msg.data.append(id)
t2 = time.time()
print(t2-t1)

t1 = time.time()
id_msg.data = id_human.tolist()
t2 = time.time()
print(t2-t1)

print(id_msg)

3.24249267578125e-05
1.6927719116210938e-05
layout: 
  dim: []
  data_offset: 0
data: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
